
#chunk loader settings
["chunk loading"]
	#The radius (in chunks) that the chunk loader will cover
	#Range: > 1
	loadingRadius = 3
	#Enable verbose logging of placements and removals of chunk loaders
	verboseLoaders = true

